In [4]:
import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

seed = 7
np.random.seed(seed)

dataset = pd.read_csv('iris.data.csv')

dataset = dataset.values
X = dataset[:,0:4].astype(float)
Y = dataset[:,4]

In [9]:
encoder = LabelEncoder()
encoder.fit(['Hema','Aravind','Janani','Jahnavi'])
encoded_Y = encoder.transform(['Janani','Jahnavi','Aravind','Hema'])
dummy_y = np_utils.to_categorical(encoded_Y)

#print(Y[:10])
print(encoded_Y[:10])
print(dummy_y[:10])

[3 2 0 1]
[[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]]


In [10]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
dummy_y = np_utils.to_categorical(encoded_Y)


In [21]:
kfold = StratifiedKFold(n_splits=10,shuffle=True,random_state=seed)
cvscores=[]
for train,test in kfold.split(X,Y):
    model = Sequential()
    model.add(Dense(10,input_dim=4,activation='relu'))
    model.add(Dense(3,activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    
    model.fit(X[train],dummy_y[train],epochs=150,batch_size=10,verbose=0)
    scores = model.evaluate(X[test],dummy_y[test],verbose=0)
    cvscores.append(scores[1] *100)
    


In [22]:
print(np.mean(cvscores))
print(np.std(cvscores))

98.0000001192
3.05505028121
